### ISSUE TITLE
urllib2 module not found on Python 3 Env

### ISSUE THREAD

**Issue by Dry8r3aD** [kssim/vim-korDic#2]
Env : Ubuntu 16.04, Python 3

gyyoon@gyyoon-Desktop$ vim 
/usr/share/vim/vim74/plugin/vim-korDic.vim 수행중 에러 발견:
  74 줄:
Traceback (most recent call last):
  File "<string>", line 5, in <module>
ImportError: No module named 'urllib2'

**Comment by kssim** [comment]
Fixed it.
